version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: res_v2
      POSTGRES_USER: res
      POSTGRES_PASSWORD: res

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  celery:
    build: .
    command: [ 'celery', '-A', 'res', 'worker','-l', 'info' ]
    volumes:
      - .:/res
    depends_on:
      - db
      - redis
    environment:
      - C_FORCE_ROOT=true
      - BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#  web:
#    build: .
#    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/res
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - ./res/.env
  celery-beat:
    build: .
    command: celery -A res beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
networks:
  default:
    external:
      name: res_food_v2_default