# Generated by Django 5.0.6 on 2024-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_customprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='country',
            new_name='location',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='success_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
