# Generated by Django 5.0.6 on 2024-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_rename_country_employeeprofile_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
