# Generated by Django 5.0.6 on 2024-06-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='state',
        ),
    ]
