# Generated by Django 5.0.6 on 2024-06-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employeeprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
