# Generated by Django 5.0.6 on 2024-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employeeprofile_email_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_contact',
            field=models.BooleanField(default=False),
        ),
    ]
