# Generated by Django 5.0.6 on 2024-06-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_profile_email_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_contact',
            field=models.CharField(blank=True, default='email', max_length=50, null=True),
        ),
    ]
