# Generated by Django 5.0.6 on 2024-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0011_alter_profile_email_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
