# Generated by Django 5.0.6 on 2024-10-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_profile_email_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_type',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'customer'), (4, 'cancel'), (3, 'admin')], default=1),
        ),
    ]
