# Generated by Django 5.0.6 on 2024-09-30 17:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0012_employeeprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
