# Generated by Django 5.0.6 on 2024-10-31 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0012_alter_profile_employee_type"),
        ("employee", "0016_district"),
    ]

    operations = []
