# Generated by Django 5.0.6 on 2024-10-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0017_merge_0012_alter_profile_employee_type_0016_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="employee_type",
            field=models.IntegerField(
                choices=[(1, "owner"), (2, "customer"), (4, "cancel"), (3, "admin")],
                default=2,
            ),
        ),
    ]
