# Generated by Django 5.0.6 on 2024-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0018_alter_profile_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
