# Generated by Django 5.0.6 on 2024-11-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0020_alter_profile_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_shipper",
            field=models.ImageField(blank=True, null=True, upload_to="avatar_shipper"),
        ),
        migrations.AddField(
            model_name="profile",
            name="driving_license",
            field=models.ImageField(blank=True, null=True, upload_to="driving_license"),
        ),
    ]
