# Generated by Django 5.0.6 on 2024-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0021_profile_avatar_shipper_profile_driving_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
