# Generated by Django 5.0.6 on 2024-11-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_cart_note"),
        ("menu", "0023_alter_size_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="menu.size"
            ),
        ),
    ]
