# Generated by Django 5.0.6 on 2024-11-03 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_cart_size"),
        ("menu", "0023_alter_size_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart", unique_together={("food_item", "size")},
        ),
    ]
