# Generated by Django 5.0.6 on 2024-11-12 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0005_alter_cart_unique_together"),
        ("vendor", "0025_openinghour"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="vendor",
            field=models.ForeignKey(
                default=25,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
            preserve_default=False,
        ),
    ]
