# Generated by Django 5.0.6 on 2024-10-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_cart_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
