# Generated by Django 5.0.6 on 2024-10-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_updated_at_transaction_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtransaction',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
