# Generated by Django 5.0.6 on 2024-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_rename_cart_cartpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtransaction",
            name="amount_cash",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subtransaction",
            name="amount_point",
            field=models.IntegerField(default=0),
        ),
    ]
