# Generated by Django 5.0.6 on 2024-11-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_alter_wallet_balance_cash_alter_wallet_balance_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.wallet",
            ),
        ),
    ]
