# Generated by Django 5.0.6 on 2024-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0009_alter_transaction_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="method",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Bank Transfer"),
                    (2, "Wallet"),
                    (3, "Paypal"),
                    (4, "Cash"),
                    (5, "Vnpay"),
                ],
                default=0,
            ),
        ),
    ]
