# Generated by Django 5.0.6 on 2024-07-23 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
