# Generated by Django 5.0.6 on 2024-07-23 09:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
