# Generated by Django 5.0.6 on 2024-07-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_fooditem_description'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('coupon_creation_date', models.DateTimeField(auto_now_add=True)),
                ('coupon_expiry_date', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_of_discount', models.CharField(choices=[('Free Delivery', 'Free Delivery'), ('Percentage', 'Percentage'), ('Refund Coin', 'Refund Coin')], default='Percentage', max_length=50)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
