# Generated by Django 5.0.6 on 2024-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_coupon_created_by_coupon_current_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
