# Generated by Django 5.0.6 on 2024-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_coupon_max_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
