# Generated by Django 5.0.6 on 2024-10-02 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0011_alter_fooditem_price"),
        ("vendor", "0013_alter_vendor_vendor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_food_items",
                to="vendor.vendor",
            ),
        ),
    ]
