# Generated by Django 5.0.6 on 2024-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0012_alter_fooditem_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="sale_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="time_range",
            field=models.CharField(
                choices=[
                    ("morning", "6:00-12:00"),
                    ("afternoon", "12:00-18:00"),
                    ("evening", "18:00-24:00"),
                    ("night", "0:00-6:00"),
                ],
                default="morning",
                max_length=10,
            ),
        ),
    ]
