# Generated by Django 5.0.6 on 2024-11-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0015_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="sizes",
            field=models.ManyToManyField(related_name="food_items", to="menu.size"),
        ),
        migrations.AlterField(
            model_name="size",
            name="food_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_items",
                to="menu.fooditem",
            ),
        ),
    ]
