# Generated by Django 5.0.6 on 2024-11-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0016_fooditem_sizes_alter_size_food_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="size",
            field=models.CharField(
                choices=[
                    ("N", "Normal"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Extra Extra Large"),
                ],
                max_length=3,
            ),
        ),
    ]
