# Generated by Django 5.0.6 on 2024-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0017_alter_size_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
