# Generated by Django 5.0.6 on 2024-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0019_fooditem_food_title_fooditem_sub_food_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="discounted_price",
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="old_price",
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
