# Generated by Django 5.0.6 on 2024-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0021_alter_fooditem_old_price_alter_fooditem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="discounted_price",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
