# Generated by Django 5.0.6 on 2024-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0022_alter_fooditem_discounted_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size", name="price", field=models.IntegerField(default=0),
        ),
    ]
