# Generated by Django 5.0.6 on 2024-11-09 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0024_remove_coupon_created_by_remove_coupon_food_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="coupon", name="user", ),
    ]
