# Generated by Django 5.0.6 on 2024-11-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0027_alter_coupon_discount_value"),
        ("vendor", "0025_openinghour"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
