# Generated by Django 5.0.6 on 2024-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order", name="subtotal", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="total_delivery_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="total_shipping_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order", name="total", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order", name="total_tax", field=models.IntegerField(default=0),
        ),
    ]
