# Generated by Django 5.0.6 on 2024-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_order_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[("In Transit", "In Transit"), ("Delivered", "Delivered")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
