# Generated by Django 5.0.6 on 2024-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_delivery_status_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="message_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Waiting for Confirmation", "Waiting for Confirmation"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                ],
                default="New",
                max_length=24,
            ),
        ),
    ]
