# Generated by Django 5.0.6 on 2024-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_message_error_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedfood",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
