# Generated by Django 5.0.6 on 2024-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_orderedfood_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderedfood", name="amount", ),
        migrations.AlterField(
            model_name="orderedfood",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderedfood",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
