# Generated by Django 5.0.6 on 2024-11-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_remove_orderedfood_amount_alter_orderedfood_price_and_more"),
        ("vendor", "0025_openinghour"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
