# Generated by Django 5.0.6 on 2024-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_payment_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Processing", "Processing"),
                    ("Waiting for Confirmation", "Waiting for Confirmation"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                ],
                default="New",
                max_length=24,
            ),
        ),
    ]
