# Generated by Django 5.0.6 on 2024-11-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_payment_completed_alter_order_status'),
        ('vendor', '0025_openinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('Processing Payment', 'Processing Payment'), ('Payment Failed', 'Payment Failed'), ('Payment Completed', 'Payment Completed'), ('Waiting for Confirmation', 'Waiting for Confirmation'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='New', max_length=24),
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
