# Generated by Django 5.0.6 on 2024-11-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status_remove_order_vendors_and_more'),
        ('vendor', '0025_openinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(to='vendor.vendor'),
        ),
    ]
