# Generated by Django 5.0.6 on 2024-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_order_shipper"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
