# Generated by Django 5.0.6 on 2024-11-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_vendors_order_vendors'),
        ('orders', '0014_order_assigned_at'),
    ]

    operations = [
    ]
