# Generated by Django 5.0.6 on 2024-11-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="attempts", field=models.IntegerField(default=0),
        ),
    ]
