# Generated by Django 5.0.6 on 2024-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0019_order_proof_image_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
